language: python
python:
  - 2.7
  - 3.3

  - 3.4
  - 3.5
  - nightly

before_install:
 - pip install numpy
 - pip install scipy cython
 - pip install coveralls

install:
 - python setup.py install

script:
 - python setup.py test
 - mpg -h

#after_success:
# - coveralls
