language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - nightly

# build-deps of sci/numpy
addons:
  apt:
    packages:
      - libsuitesparse-dev
      - liblapack-dev
      - libblas-dev
      - gfortran

before_install:
 - pip install numpy
 - pip install scipy cython
 - pip install coveralls

script:
 - python setup.py install
 - python setup.py test
 - mpg -h

#after_success:
# - coveralls
