language: python

sudo: required
dist: trusty

python:
  - 3.4

# build-deps of sci/numpy
addons:
  apt:
    packages:
      - python3-numpy
      - python3-scipy
      - python3-pip
      - cython

before_install:
 - deactivate
 - pip install coveralls

script:
 - deactivate
 - python setup.py install
 - python setup.py test
 - mpg -h

#after_success:
# - coveralls
